import { ShipmentDetail } from './types';

// Mock data (could be replaced with API calls)
export const mockShipmentDetails: Record<string, ShipmentDetail> = {
  "SHP-001": {
    id: "SHP-001",
    orderId: "ORD-001",
    customer: "John Smith",
    email: "john.smith@email.com",
    destination: "New York, NY",
    fullAddress: "123 Main St, New York, NY 10001",
    carrier: "FedEx",
    trackingNumber: "1234567890",
    shipDate: "2024-01-15",
    estimatedDelivery: "2024-01-17",
    actualDelivery: "2024-01-17",
    status: "delivered",
    priority: "normal",
    weight: 2.5,
    dimensions: '12" x 8" x 6"',
    items: 3,
    packageType: "Standard Box",
    specialInstructions: "Leave at front door",
  },
  "SHP-002": {
    id: "SHP-002",
    orderId: "ORD-002",
    customer: "Sarah Johnson",
    email: "sarah.j@email.com",
    destination: "Los Angeles, CA",
    fullAddress: "456 Oak Ave, Los Angeles, CA 90210",
    carrier: "UPS",
    trackingNumber: "0987654321",
    shipDate: "2024-01-16",
    estimatedDelivery: "2024-01-19",
    status: "shipped",
    priority: "high",
    weight: 1.8,
    dimensions: '10" x 6" x 4"',
    items: 2,
    packageType: "Padded Envelope",
  },
  "SHP-003": {
    id: "SHP-003",
    orderId: "ORD-003",
    customer: "Mike Davis",
    email: "mike.davis@email.com",
    destination: "Chicago, IL",
    fullAddress: "789 Pine St, Chicago, IL 60601",
    carrier: "DHL",
    trackingNumber: "5555666777",
    shipDate: "2024-01-17",
    estimatedDelivery: "2024-01-20",
    status: "packed",
    priority: "urgent",
    weight: 0.5,
    dimensions: '8" x 4" x 2"',
    items: 1,
    packageType: "Small Package",
    specialInstructions: "Signature required",
  },
};